### ISSUE TITLE
config doesn't get parsed if $XDG_DATA_HOME/strata/lua doesn't exist.

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [StrataWM/strata#53]
https://github.com/StrataWM/strata/blob/d9d014c30fddc60e307923c206cec40ee2a6f94d/src/main.rs#L38-L46

`lib_dir` is `None` if `$XDG_DATA_HOME/strata/lua` doesn't exists

**Comment by anantnrg** [comment]
Yep, that's expected to happen. You need to either copy the `lua` folder to `$XDG_DATA_HOME/strata/lua` or install by running `sudo make install`. Sorry for making you run circles around this. I'll update the README right now.

**Comment by MurdeRM3L0DY** [comment]
oh my bad, the lua folder contains other missing modules, like `action` etc...
