### ISSUE TITLE
Consider adding a `SECURITY.md`

### ISSUE THREAD

**Issue by MultisampledNight** [StrataWM/strata#64]
[`CONTRIBUTING.md` in the section `How do I submit a good bug report`](https://github.com/StrataWM/strata/blob/8c9dac0d9316785c0f42a2a906b4d759f27d5c78/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) lists an email on where to report security sensitive issues. Since that is quite buried in `CONTRIBUTING.md`, it might make sense to add a `SECURITY.md`, so that a person in a hurry can report a security issue over the `Security` tab.

**Comment by anantnrg** [comment]
Oh okay, I'll look into it. Thanks :)

**Comment by anantnrg** [comment]
I've added a sample one for now. I'll modify it later on. Thanks for the reminder tho :)
